steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hellonodejs:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hellonodejs:$SHORT_SHA']
images: ['gcr.io/$PROJECT_ID/hellonodejs:$SHORT_SHA']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=istio-2.yaml
  - --image=gcr.io/$PROJECT_ID/hellonodejs:$SHORT_SHA
  - --location=${_LOCATION}
  - --cluster=${_CLUSTER}
