steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hellonodejs:local', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hellonodejs:local']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=istio-2.yaml
  - --image=gcr.io/$PROJECT_ID/hellonodejs:local
  - --location=${_LOCATION}
  - --cluster=${_CLUSTER}
images: ['gcr.io/$PROJECT_ID/hellonodejs:local']
