steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build image
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hellonodejs:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: Push to GCR
  args: ['push', 'gcr.io/$PROJECT_ID/hellonodejs:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  id: Copy the new yaml file
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    cd baseline &&
    cp depl.yaml depl-1.yaml
    sed "s/COMMIT_SHA/${SHORT_SHA}/g" > depl-1.yaml
    cp depl-1.yaml ../app/depl.yaml    
images: ['gcr.io/$PROJECT_ID/hellonodejs:$SHORT_SHA']
